### ISSUE TITLE
Is this plugin available at jenkins plugins?

### ISSUE THREAD

**Issue by quasarea** [adiesner/bitbucket-pr-coverage-status-plugin#2]
Just tried to look for this plugin at jenkins plugins and the only record I got is `GitHub Pull Request Coverage Status Addon 1.10.0`, also all releases here are named as github-pr-coverage-status-* ? so I'm puzzled - should I manually replace existing extension with this one or something? why name starts with github not bitbucket/stash?

**Comment by adiesner** [comment]
This plugin is currently not available at jenkins plugins. It is a fork of [github-pr-coverage-status-plugin](https://github.com/jenkinsci/github-pr-coverage-status-plugin) but I replaced all github related stuff with the bitbucket server / stash api. 

I never created an official release, and never applied to be listed at jenkins plugins since I never got the time to give this repository the finishing touch. It is running in our company and doing its job - but I am not satisfied with the code. 

I can provide an *.hpi file for manual installation in the jenkins - and with enough feedback I might even continue the development.

**Comment by quasarea** [comment]
Having an hpi would be great, especially if you could sort the naming, so it would be unique (like bitbucket-pr-coverage-status-plugin). Saying that I'm not sure if I can make use of it in current shape. My coverage reports are coming either from dotCover or OpenCover projects. I managed to extract the values of total cover from those reports and trying to sculpture something that would look like yours https://raw.githubusercontent.com/adiesner/bitbucket-pr-coverage-status-plugin/master/screenshot.png image. I wonder if making it both coverage and versioning system agnostic would not benefit the project. Like coverage-status-plugin that you can call from groovy pipeline with value/branch provided - could store value for a build/branch and then adapt to currently provided data. Anyway I'm trying to solve it in groovy shared library, so maybe there is no need for your efforts.

**Comment by adiesner** [comment]
Sorry for the delay. I just uploaded a hpi file that is currently used at my company.
https://github.com/adiesner/bitbucket-pr-coverage-status-plugin/releases/tag/bitbucket-pr-coverage-status-0.0.1
